language: r
sudo: false
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libglpk-dev
      - libgmp3-dev
      - libxml2-dev

env:
  global:
    - ALLOWED_NOTES=1

notifications:
  email:
    recipients:
     - alerts@jumpingrivers.support
    on_success: change
    on_failure: change

before_install:
  - tlmgr install fancyvrb units
  - sudo apt-get install -y ghostscript

before_script:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/test_deploy.sh
  - if [ ${TRAVIS_PULL_REQUEST} = "false" ] && [ $TRAVIS_BRANCH = "master" ]; then bash test_deploy.sh; fi
  - rm test_deploy.sh

script:
  - Rscript -e "source('https://raw.githubusercontent.com/jr-packages/drat/master/script.R')"

after_success:
  - wget https://raw.githubusercontent.com/jr-packages/drat/master/deploy.sh
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
